apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: flux-system
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376